### ISSUE TITLE
Foundation / jQuery not initialized - Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by Nimoi** [JVMartin/angel#3]
I tried adding a responsive top-bar menu, the realized jQuery nor Foundation were available. To fix I added a `bootstrap.js` to `/resources/assets/js/app`:

```
// Window-bound objects.
window.$ = window.jQuery = require('jquery');

// External packages - order matters.
require('foundation-sites');
```

And added `import './bootstrap';` to the top of `/resources/assets/js/app/app.js`. Seems like common sense now, but I assumed jQuery/Foundation would be available out of the box like in the admin panel.

**Comment by JVMartin** [comment]
[Done, thank you!](https://github.com/JVMartin/angel/commit/abde6c44a524cb355a493975ce9e0110e1588c6c)
